Models/MyCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace SachViet.Models
{
    public class MyCart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();
        public virtual void AddItem(Book book, int quantity)
        {
            CartLine line = Lines.Where(b => b.Book.BookID == book.BookID).FirstOrDefault();
            if(line == null)
            {
                Lines.Add(new CartLine { Book = book, Quantity = quantity });
            }
            else
            {
                line.Quantity += quantity;
            }
        }
        public virtual void RemoveLine(Book book) => Lines.RemoveAll(l => l.Book.BookID == book.BookID);
        public decimal ComputeTotalValue() => Lines.Sum(e => e.Book.Price * e.Quantity);
        public virtual void Clear() => Lines.Clear();
    }
    public class CartLine
    {
        public int CartLineID { get; set; }
        public Book Book { get; set; }
        public int Quantity { get; set; }
    }
}

Controllers/OrderController.cs
using SachViet.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace SachViet.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private MyCart cart;
        public OrderController(IOrderRepository repoService, MyCart cartService)
        {
            repository = repoService;
            cart = cartService;
        }
        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Giỏ hàng đang trống kìa");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                cart.Clear();
                return RedirectToPage("/Completed", new { orderId = order.OrderID });
            }
            else
            {
                return View();
            }
        }
    }
}

Pages/Completed.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SachViet.Pages
{
    public class CompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/MyCart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SachViet.MyTagHelper;
using SachViet.Models;
using System.Linq;

namespace SachViet.Pages
{
    public class MyCartModel : PageModel
    {
        private IBooksLibRepository repository;

        public MyCartModel(IBooksLibRepository repo, MyCart myCartService)
        {
            repository = repo;
            myCart = myCartService;
        }

        public MyCart myCart { get; set; }
        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            //
            //myCart = HttpContext.Session.GetJson<MyCart>("mycart") ?? new MyCart();
            //
        }
        [HttpPost]
        public IActionResult OnPost(long bookId, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(b => b.BookID == bookId);
            myCart.AddItem(book, 1);
            //
            //HttpContext.Session.SetJson("mycart", myCart);
            //       
            return RedirectToPage(new { returnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(long bookId, string returnUrl)
        {
            myCart.RemoveLine(myCart.Lines.First(cl => cl.Book.BookID == bookId).Book);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/_MyCartLayout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SachViet.Pages
{
    public class _MyCartLayoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/_ViewImports.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SachViet.Pages
{
    public class _ViewImportsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/_ViewStart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SachViet.Pages
{
    public class _ViewStartModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Completed.cshtml
@page
<div class="text-center">
    <h3>Cảm ơn đã mua hàng - Thank for shopping</h3>
    <p>Chúng tôi sẽ cố gắng giao sách đến cho bạn nhanh nhất có thể</p>
    <p>Cảm ơn đã chờ đợi ♥</p>
    
    <img src="~/images/thanks.png" height="200"/>
</div>
<div class="text-center">
    <a class="btn btn-info" asp-controller="Home">Trở về cửa hàng</a>
</div>

@functions {
    [BindProperty(SupportsGet = true)]
    public string OrderId { get; set; }
}

Pages/MyCart.cshtml
@page
@model MyCartModel
<h2>Giỏ Hàng</h2>
<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <th></th>
            <th>Số lượng</th>
            <th>Tên sách</th>
            <th class="text-right">Giá</th>
            <th class="text-right"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.myCart.Lines)
        {
            <tr>
                <td class="text-center"><img src="@line.Book.ImgPath" width="50" /></td>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Book.Title</td>
                <td class="text-right">@line.Book.Price.ToString("c")</td>
                <td class="text-right">@((line.Quantity * line.Book.Price).ToString("c"))</td>
                <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="BookID" value="@line.Book.BookID" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Hủy</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Tổng tiền</td>
            <td class="text-right">
                @Model.myCart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-info" href="@Model.ReturnUrl">Trở lại</a>
    <a class="btn btn-info" asp-action="Checkout" asp-controller="Order">Thanh toán</a>
</div>

Pages/_MyCartLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sách Việt</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet"/>
</head>
<body>
    <div class="bg-wood text-white p-2">
        <span class="navbar-brand ml-2">SÁCH VIỆT</span>
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>